version: '3.8'

services:
  db:
    container_name: bigo_db
    image: blabla1337/mysql
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./db_volumes/conf.d:/etc/mysql/conf.d
      - ./db_volumes/data:/var/lib/mysql
      - ./db_volumes/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    networks:
      - bigo_network

  application:
    build: .
    restart: always
    ports:
      - '8000:8000'
    depends_on:
      - db
    container_name: test_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - bigo_network

networks:
  bigo_network: