version: '3.8'

services:
  db:
    container_name: bigo_db
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      TZ: Asia/Seoul
    volumes:
      - ./db_volumes/conf.d:/etc/mysql/conf.d
      - ./db_volumes/data:/var/lib/mysql
      - ./db_volumes/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '3307:3306'
    networks:
      - bigo_network

networks:
  bigo_network: